### ISSUE TITLE
setByValue: doesn't work in IE 

### ISSUE THREAD

**Issue by kevin-krug-sociomantic** [sociomantic-tsunami/flounder#102]
## current

as of latest release `0.8.2` (https://github.com/sociomantic-tsunami/flounder/releases) `setByValue` does not work in IE. tested on Windows 8.1 on IE 11.0 via browserstack. 

instantiated a native Flounder and set value via `setByValue` api method:
```
var flounder = new Flounder( <targetDOMelement>, { data: [1,2,3] } );
flounder.setByValue( 2 );
```
result:

![screen shot 2016-06-28 at 12 51 08](https://cloud.githubusercontent.com/assets/6839359/16412989/63ceca40-3d2f-11e6-947c-d163efab95ca.png)

in other browsers `2` is selected as expected

## wanted 

add IE support for `setByValue`

**Comment by mousemke** [comment]
can you test with the `0.8.3` branch? i'm pushing on `1.0.0`, but dont want to rush it, so i can give you a quick fix.  however from what i can see it works fine. Also, is there anything in the console? maybe some code? any more info?

just tested at `0.8.3`

IE11, Win7
IE10, Win7
IE9, Win7


steps to reproduce:

+ go to the flounder demo page `http://flounderjs.com/demo`
+ open the console (f12)
+ grab a flounder
+ double check the version is `0.8.3`
+ set a new data set
+ set a new value
+ just to double check, set another by string 


```js
var _f = $('.flounder')[0].flounder
_f.version;
_f.reconfigure( { data:[1,2,3,4,4]} );
_f.setByValue( 2 );
_f.setByValue( '3' );
```

**Comment by kevin-krug-sociomantic** [comment]
@mousemke thanks for looking into this! i can confirm that your example works. In my example i immediately use `setByValue` after an instantiation. E.g I did this:

- went to http://flounderjs.com/demo
- opened IE inspector (in browserstack e.g. checking Win8 IE10)
- added a new div to the demo page (in my below example i add a css 'test' class)
- instanitated a flounder on this new div (e.g. with data [1,2,3,4]) and `setByValue` (e.g. 3)

result

![screen shot 2016-06-28 at 16 33 41](https://cloud.githubusercontent.com/assets/6839359/16419488/327ff65c-3d4e-11e6-9227-e8b4a46ae9bc.png)

**Comment by kevin-krug-sociomantic** [comment]
confirmed that this happens with `0.8.3` `_f.version` returns  `"0.8.3"`

**Comment by mousemke** [comment]
no time to look deeper, but i've managed to reproduce the issue

**Comment by kevin-krug-sociomantic** [comment]
@mousemke thanks for looking into this! would be greatly appreciated if you could check it, cheers!

**Comment by mousemke** [comment]
fixed.  ie was having trouble grabbing indexes of elements that were (apparently) not mounted yet

https://github.com/sociomantic-tsunami/flounder/releases/tag/0.8.5
