### ISSUE TITLE
multitag flounder: setByValue deselects option if already selected

### ISSUE THREAD

**Issue by kevin-krug-sociomantic** [sociomantic-tsunami/flounder#109]
not sure if this is expected behaviour, if so i guess the docs should be updated. 

## current 

if you select an option programmatically via setByValue, then that option is removed from the selected, if previously selecte. 

e.g if you check the demo http://flounderjs.com/demo/ and console execute the following: 

![screen shot 2016-07-13 at 11 42 31](https://cloud.githubusercontent.com/assets/6839359/16799168/b9ea61d4-48ef-11e6-9631-7bb3dc3e7e1b.png)

you get:
![screen shot 2016-07-13 at 11 42 09](https://cloud.githubusercontent.com/assets/6839359/16799174/be57e37c-48ef-11e6-8034-0a68cb41affd.png)

so "category" was deselected.

**Comment by mousemke** [comment]
i would appreciate other views on the matter.  i think that is good behavior, but maybe we need a force select/deselect api function? or to rename setValue, etc

**Comment by mousemke** [comment]
due to the fact that this is a discussion matter and it has been largely abandoned, it is being removed from the `1.0.0`milestone so we can ship this weekend.  Holla if you believe it is still actionable
