### ISSUE TITLE
multitag flounder : navigation keys incorrectly add an items to the empty dropdown

### ISSUE THREAD

**Issue by kevin-krug-sociomantic** [sociomantic-tsunami/flounder#111]
***to reproduce:***

1. go to flounder demo http://flounderjs.com/demo/: 

2. select all options in the multitag dropdown . result:

![screen shot 2016-07-18 at 12 16 44](https://cloud.githubusercontent.com/assets/6839359/16911906/82718d72-4ce1-11e6-8755-f65653bc52f2.png)

3. press `<down`>. result:

![screen shot 2016-07-18 at 12 15 19](https://cloud.githubusercontent.com/assets/6839359/16911875/5bc2ff6c-4ce1-11e6-90a6-aa9b3ee3f8bb.png)

**Comment by mousemke** [comment]
can you pull `dev` and see if this is still an issue?  looks good on my machine (mots of `multipleTags` things have changed)

**Comment by mousemke** [comment]
@kevin-krug-sociomantic still an issue?

**Comment by mousemke** [comment]
due to the fact that this is a discussion matter and it has been largely abandoned, it is being removed from the `1.0.0`milestone so we can ship this weekend.  Holla if you believe it is still actionable

**Comment by mousemke** [comment]
fixed in `1.0.0`
