### ISSUE TITLE
bug: js error on selection of a flounder html option

### ISSUE THREAD

**Issue by kevin-krug-sociomantic** [sociomantic-tsunami/flounder#119]
## current bug

when clicking/selecting an html option from a flounder dropdown (allowHTML set to true), the js error is thrown:

`Cannot read property 'selected' of undefined`

 and the option is not selected.

e.g. say you initilaze flounder with (<targetDOMelement> being e.g. a input tag):

var flounder = new Flounder( <targetDOMelement>, { data: ['1','2','<button>click me</button>'], allowHTML : true } );

and your click target is the button itself:
![screen shot 2016-11-04 at 16 40 14](https://cloud.githubusercontent.com/assets/6839359/20011883/6351f0f4-a2ad-11e6-8410-7c211d970b2e.png)

## bug origin

the flounder method `setSelectValueClick` assumes that its target is ALWAYS the option tag which has the `data-index` attribute set. However as this is not the case in situtations as above, the `setSelectValueClick`-code below fails:

```
index = target.getAttribute('data-index')
selectedOption = refs.selectOptions[index];
selectedOption.selected = selectedOption.selected === true ? false : true;
```

## wanted

fix

**Comment by mousemke** [comment]
That's an interesting usage of the allowHTML flag, but that was intended mostly for formatting and not for other inputs.  To prettify it.  Having a button (or any other intractable DOM element) doesn't confirm with the native and accessibility standards that the project has laid out

**Comment by kevin-krug-sociomantic** [comment]
fair enough @mousemke 😄
