### ISSUE TITLE
Flounder should hide flounder section header when no results

### ISSUE THREAD

**Issue by damian-rodriguez-sociomantic** [sociomantic-tsunami/flounder#120]
section header should also be hidden when searching and no matches found 

![screen shot 2016-11-09 at 11 49 06](https://cloud.githubusercontent.com/assets/6596205/20136136/8f35387e-a673-11e6-9343-59735b254666.png)

**Comment by vasileios-karavasilis-sociomantic** [comment]
I can not assign this issue to myself (permission problem probably), so if anyone has write access, please assign this issue to me.

**Comment by mousemke** [comment]
i cant.  @dylan-cromwell-sociomantic maybe needs to add you to the tsunami org? whne i open the @ prompt, only 5 Soc ppl show up
