### ISSUE TITLE
[Multitag] Pressing ENTER on exact match should select relevant option

### ISSUE THREAD

**Issue by conor-cafferkey-sociomantic** [sociomantic-tsunami/flounder#128]
### Problem
Normally typing the exact string of an option and pressing ENTER selects that option. There is an edge case where we have two (or more) options one of which is a substring of the other.

### Currently

If we have two options `abc` and `abcdefg`, typing `abc` and ENTER does not select the relevant option.

### Wanted
Exact match always gets selected.

**Comment by vasileios-karavasilis-sociomantic** [comment]
Lets assume that the check box has: [ABC, ABCDE, KLM].
The current behaviour is this one:
1. User enters: KL\n: selects KLM.
2. User enters: ABCD\n: selects ABCDE.
3. User enters: ABC\n: nothing is selected. It should select ABC.
4. User enters: AB\n: nothing is selected. What we should do now.

My question is about 4. Should we select or not ABC? I think we should select ABC (i.e. the string that matches and has the minimum length across the matches).

**Comment by conor-cafferkey-sociomantic** [comment]
> User enters: AB\n: nothing is selected. What we should do now.

The current implementation dictates that nothing should happen. 

That said, personally I think what you’re suggesting makes more sense. @mousemke any thoughts on that?

**Comment by mousemke** [comment]
i would say that unless there is only one left it selects nothing.  this reduces user error (type half, get something you dont want).  you can always click

**Comment by vasileios-karavasilis-sociomantic** [comment]
OK, so, in case we have more than one matches, it will select something something only if we have exact match. My other question is if we will distinguish upper and lower case letters. E.g. if the checkbox has [ABC, ABCD] and user gives "abc", should we match this with ABC?

**Comment by mousemke** [comment]
maybe an option for case-sensitivity?

**Comment by conor-cafferkey-sociomantic** [comment]
Should definitely be case insensitive by default. I think it’s gonna be extremely rare that you’d want case sensitivity. If we wanna add that option it should under be a separate issue from this one.

**Comment by vasileios-karavasilis-sociomantic** [comment]
Yes, I also think that case insensitive is the current behaviour and if we need this, we should create another issue.
