### ISSUE TITLE
[Styling] Make sure BEM is used for all CSS class names

### ISSUE THREAD

**Issue by conor-cafferkey-sociomantic** [sociomantic-tsunami/flounder#137]
### Currently

CSS class naming in `flounder-structure.css` could be better.

### Wanted
Make sure all class names conform to [BEM](http://getbem.com/introduction/)

**Comment by mousemke** [comment]
Theres a 2nd solution.  Switch gulp to webpack and use scoped css

**Comment by conor-cafferkey-sociomantic** [comment]
Yep I like that solution. Maybe we open a separate switch-gulp-to-webpack issue?

**Comment by mousemke** [comment]
i will close this issue to push forward on webpack
