### ISSUE TITLE
Performance issue when populating a large number of items

### ISSUE THREAD

**Issue by tar-viturawong-sociomantic** [sociomantic-tsunami/flounder#148]
We have a use case of populating 4,000+ items. This is currently extremely slow in Flounder (opening the dropdown takes 1 full second). 

I'm guessing that not all items have to be rendered at once, or that some kind of "show more" functionality could be built in?

Wanted: from :turtle: to :rabbit2: :racehorse: :racing_car: :bullettrain_front: :small_airplane: :1st_place_medal:

**Comment by emad-alam-sociomantic** [comment]
@conor-cafferkey-sociomantic Just to give some insights on this, the fact that we pre-render all the items as live DOM elements and then add/remove hidden class to toggle `display : none`, causing a repaint on the entire list of DOM elements (even though we just add/remove class from the parent, a repaint will happen for the entire list of children), is the real performance bottleneck. AFAIK, the only solution to this issue would be to render items in chunks and do on demand chunked rendering (example when scrolling inside the flounder list), or to achieve this by somehow having a css setup that doesn't cause a forced reflow. Below are the sample from the profiling and a demo to indicate the same sluggishness while removing the hidden class using the developer tools.

![screen shot 2017-07-24 at 11 23 03](https://user-images.githubusercontent.com/17457130/28517492-d64f1e4e-7064-11e7-9157-b83643b43a53.png)
![flounder](https://user-images.githubusercontent.com/17457130/28517493-d651617c-7064-11e7-92fa-8fc71852559d.gif)

**Comment by conor-cafferkey-sociomantic** [comment]
There is no single bottleneck causing the performance issue above so I’ve created a [Performance milestone](https://github.com/sociomantic-tsunami/flounder/milestone/16) with specific issues to tackle this and other performance issues with large datasets.
