### ISSUE TITLE
[Events] On open selected option should always be visible

### ISSUE THREAD

**Issue by conor-cafferkey-sociomantic** [sociomantic-tsunami/flounder#157]
### Currently

Consider a Flounder with a long list of options that must be scrolled. When we open the dropdown the scroll position is either at the top of the list (if we have not interacted with it) or wherever we last left off. 

### Problem

This means the currently selected option is not always in view.

### Wanted

Native behavior (to be verified): dropdown always opens with selected option in view.

**Comment by mousemke** [comment]
relavent https://github.com/sociomantic-tsunami/flounder/blob/master/src/core/utils.js#L323-L346
