### ISSUE TITLE
search is extremely slow when multipleTags prop is set

### ISSUE THREAD

**Issue by emad-alam-sociomantic** [sociomantic-tsunami/flounder#158]
Currently
---
Flounder dropdown with `{ search : true, multipleTags : true }`, seem to break the search functionality (unresponsive UI) with large data sets (~6000), and the component is unusable in this state.

Wanted
---
Fix it, make the calls non-blocking to the UI.

**Comment by conor-cafferkey-sociomantic** [comment]
Looks like the `filterSelected` function we introduced for https://github.com/sociomantic-tsunami/flounder/issues/126 is the main culprit here
