### ISSUE TITLE
[Performance] Defer calling focus on flounder main div and search input

### ISSUE THREAD

**Issue by conor-cafferkey-sociomantic** [sociomantic-tsunami/flounder#178]
### Currently

Calling focus on the main Flounder div and on the flounder search input is very slow when we have a very large dataset ( ~12,000 options split into sections; tested in Chrome)

### Problem

Flounder main div has thousands of child nodes so makes sense that this should be slow. 

Not clear why focusing on the search input should be so slow...

### Wanted

Use `setTimeout` to defer focusing on either one.

**Comment by mousemke** [comment]
i have not looked deeply into this issue, but to just share a nugget to keep in mind from similar issues, a lot of the focus trading is for accessibility reasons

**Comment by conor-cafferkey-sociomantic** [comment]
Since this is a fairly simple and low-risk change let’s implement as a quick perf win and release independently of the [other performance improvements](https://github.com/sociomantic-tsunami/flounder/milestone/16) that will come later.
