### ISSUE TITLE
Support custom html templates for list item

### ISSUE THREAD

**Issue by kristina-kurshakova-sociomantic** [sociomantic-tsunami/flounder#54]
There is a need to customise presentation of list item, through passing html template through options.

**Comment by mousemke** [comment]
ok, so this issue is being resolved by adding an allowHTML flag in the config options.

**Comment by mousemke** [comment]
closes with https://github.com/sociomantic-tsunami/flounder/commit/e725eb5b7bddfa1f26b6889811da690915caca1d
