### ISSUE TITLE
React Flounder issues

### ISSUE THREAD

**Issue by avraam-mavridis-sociomantic** [sociomantic-tsunami/flounder#56]
Right now the dist file of React-Flounder contains React and React-Dom itself and is kinda huge. 

My suggestion is to split Flounder to `flounder-core` and `flounder-react`, (maybe the same should happen for `jquery` etc)
and in case of react and react-dom move it from `devDependencies` to `peerDepedencies`. React-Flounder will have Core-Flounder as dependency.

Having separate repos for React (and the other frameworks) will make things much simpler, we will be able to:

-Use Flounder as dependency in our projects easier without having to include the huge dist file or using the src.
-Install it `npm i` without installing unrelated dependencies e.g. jQuery in our react Projects.
-Write tests for Flounder  (e.g.with [Enzyme](http://airbnb.io/enzyme/) that we are using in the internal projects) since right now the tests are only for the core.
-And without being 100% sure but I think also build tools that support `tree-shaking` like Webpack and Rollup can take advantage of this structure to not include in the build, parts of `Flounder` core that are not used.
-Moving flounder-core to different repo/project will make it easier to write framework-specific wrappers by us or by the community, e.g. Angular, Cycle etc

**Comment by dilkROM** [comment]
@avraam-mavridis-sociomantic you definitely are making a good case here. I am 100% in favor though I will admit you are much more involved in the details than I so I can't pretend to play Devil's Advocate anyway.

As for Tsunami repos... is it fine that these two repos just live side by side in Tsunami Org? They don't require their own "parent", correct?

Question may seem silly but if you're saying "correct" then I am fine to assist in the creation / split of the current Flounder repo into two more specific ones.

@mousemke are you having a stance on this?

**Comment by mousemke** [comment]
Founder/repo is the classic way to do it, but tsunami/founder, tsunami/founder-react, etc is good too. The other (less good) idea would be to remove the react dist because it gets packed with react. In its current state, anyone using the react version should use the /src file

**Comment by dilkROM** [comment]
Yeah, if we did "flounder/repo" we'd need to also do this for all our OS projects to maintain consistency, and the maintenance of that (as Tsunami grows) would get a bit out of hand. So if you deem that "tsunami/repo" and "tsunami/other-repo" is sufficient I guess I would push for that.

@leandro-lucarella-sociomantic do you have any thoughts / tips here? Your insight might be valuable.

**Comment by avraam-mavridis-sociomantic** [comment]
@dilkROM 
I like `tsunami/flounder`, `tsunami/flounder-react` ...

Facebook follows the same pattern for react and react-devtools  https://github.com/facebook?utf8=%E2%9C%93&query=react

(2-3 internal projects that want to use flounder-react will benefit from this splitting approach)

**Comment by avraam-mavridis-sociomantic** [comment]
Maybe @zsolt-nagy-sociomantic has some thoughts on the issue?

**Comment by zsolt-nagy-sociomantic** [comment]
@avraam-mavridis-sociomantic I am more interested in the idea you described in this issue, which is great and is 100% supported.

The repository names `flounder` and `flounder-react` seem to be correct, this way we can use just the core flounder when needed, and the updates of `flounder-react` do not affect users of `flounder`.

**Comment by leandro-lucarella-sociomantic** [comment]
Also :+1: to having all in tsunami. I would consider letting projects leave the *tsunami* namespace if they eventually *graduate*, meaning the company stops being the main maintainer of a project, and just an eventual contributor (if at all).

**Comment by mousemke** [comment]
bump.  any movement on this?

**Comment by avraam-mavridis-sociomantic** [comment]
@dilkROM @leandro-lucarella-sociomantic  can we have the repo(s) for react ?

**Comment by leandro-lucarella-sociomantic** [comment]
Could you follow the internal guideline to request a new repo? If you don't know what I am talking about please contact me privately.

**Comment by avraam-mavridis-sociomantic** [comment]
I am closing the issue. The repo is here https://github.com/sociomantic-tsunami/flounder-react
