### ISSUE TITLE
setValueDefault in setDefaultOption returns null defaultValue, crashes Flounder

### ISSUE THREAD

**Issue by jolene-borrelli-sociomantic** [sociomantic-tsunami/flounder#57]
While the Flounder markup is being built in the `buildDom`method, a default value is obtained by calling `setDefaultOption`. `setDefaultOption` is passed an object containing data relevant to an option in the Flounder dropdown.

If an object with a defaultValue property is passed to `setDefaultOption`, an inner method called `setValueDefault` is used to find the index of this defaultValue in an array of available options. If the option does not exist, the defaultValue is set to null. 

This is a bit problematic, since the subsequent lines in `buildDom` expect a defaultValue object with an index, text and value properties. Since defaultValue has a value of null, Flounder crashes and produces the error "Cannot read property 'value' of null".

It would be nice to have some options instead of setting the defaultValue to null given the above scenario. Perhaps defaulting to a blank option, the first option or an option that reads 'custom', I am not entirely sure. 

A real world example of this situation...

A user writes a custom font-family in their CSS. When Flounder attempts to match this CSS to an option in a font-family dropdown menu, it fails. This would indicate that custom CSS that is usually translated to a dropdown option and/or set via a dropdown cannot be manually edited without causing Flounder to crash.

**Comment by mousemke** [comment]
closed with 0.6.2 https://github.com/sociomantic-tsunami/flounder/releases/tag/0.6.2
