### ISSUE TITLE
Set empty value

### ISSUE THREAD

**Issue by kristina-kurshakova-sociomantic** [sociomantic-tsunami/flounder#59]
**Currently**
It's not possible to set empty value, i.e. to make flounder unselected.

**Wanted**
The ability to clear value. 
*Would be nice*: To pass selected value on instantiation, if there is no one then show no selected element.

**Comment by mousemke** [comment]
what settings are you using? placeholder is pretty high on the default priority, but if there is no placeholder, then last default is the first element

**Comment by kristina-kurshakova-sociomantic** [comment]
@mousemke i updated the question.

**Comment by mousemke** [comment]
it is not possible to have nothing selected (unless you use the multiple option), since that is also not possible with native select boxes.  Flounder fakes a placeholder by using a blank option as a slug.  So I guess (if i understand this) my suggestions would be to either add a placeholder (better option) or do something around `multiple`

**Comment by kristina-kurshakova-sociomantic** [comment]
What do you mean "add a placeholder"? If i pass a placeholder it will still choose first element and will not allow empty value. 

Anyway, is it possible to support empty value (or unset ) in proper way?

**Comment by kristina-kurshakova-sociomantic** [comment]
To support empty value suggestion, it is also requested in case of default select element http://stackoverflow.com/questions/8605516/default-select-option-as-blank

**Comment by kristina-kurshakova-sociomantic** [comment]
Ok, understood. So basically, if you need to support empty value, you need to pass a placeholder, otherwise default placeholder will not be used. 

My suggestion is to make more clear in api. Introduce a flag like 'allowEmptyValue' and show default placeholder if it is not passed in options.

**Comment by mousemke** [comment]
ok.  i have a solution.  In the same way the defaults have a priority, I would add a new value.  
instead of `placeholder: ''` (which _should_ do the same thing, dont think it does), we alllow `defaultEmpty: true`


@kristina-kurshakova-sociomantic does this solve the issue?

**Comment by kristina-kurshakova-sociomantic** [comment]
@mousemke yes! thank you
