### ISSUE TITLE
Value not set if user selects dropdown option by typing

### ISSUE THREAD

**Issue by jolene-borrelli-sociomantic** [sociomantic-tsunami/flounder#60]
A dropdown option can be selected by focusing on a Flounder and typing in the first few letters of the value. However, once this option is selected, its value is not set via the bound onSelect method.

The problem occurs in here

```

    setSelectValue: function setSelectValue(obj, e) {
        var refs = this.refs;
        var keyCode = undefined;

        if (e) // click
            {
                this.setSelectValueClick(e);
            } else // keypress
            {
                keyCode = obj.keyCode;
                this.setSelectValueButton(obj);
            }

        this.displaySelected(refs.selected, refs);

        if (!this.___programmaticClick) {
            // tab, shift, ctrl, alt, caps, cmd
            var nonKeys = [9, 16, 17, 18, 20, 91];

            if (e || obj.type === 'blur' || keyCode && nonKeys.indexOf(keyCode) === -1) {
                if (this.toggleList.justOpened && !e) {
                    this.toggleList.justOpened = false;
                } else {
                    try {
                        this.onSelect(e, this.getSelectedValues());
                    } catch (e) {
                        console.log('something may be wrong in "onSelect"', e);
                    }
                }
            }
        }

        this.___programmaticClick = false;
    },
```

If the selection of the dropdown option is not an event, `this.onSelect` is never called.

**Comment by mousemke** [comment]
so. i've had a sec to look at the issue. a big reason it checks for blur is to _filter out_ the change function.  We don't want onSelect to fire when people are cycling through. (i.e. press down, run onSelect, press down, run onSelect, press down, run onSelect, forever and ever).

so the trick will be filtering the right keycodes

**Comment by mousemke** [comment]
ok.  we're calling this the last one of 0.6.3.  sorry @jolene-borrelli-sociomantic for closing the PR, but more was needed than that.  it's now working locally.  only thing left to do is fix onSelect when you hit enter and it'll be pushed
