### ISSUE TITLE
`disabled` option not work with complex data

### ISSUE THREAD

**Issue by andrei-placinta-sociomantic** [sociomantic-tsunami/flounder#66]
When flounder is initialized with complex data options (with grouping). And that data contains some options with `disabled` flag. These options will not be disabled.

**Steps to reproduce**
- init flounder with options: (note - 2nd option is disabled)
```
[
    {
        header : 'Header 1',
        data : [ { value: 1, text: 'one' }, { value: 2, text: 'two', disabled: true } ]
    },
    {
        header : 'Header 2',
        data : [ { value: 3, text: 'three' } ]
    }
]
```
- then you are able to select 2nd option

**Comment by mousemke** [comment]
i imagine https://github.com/sociomantic-tsunami/flounder/issues/65 is related to this.  I have a typefix on the way, and the other issue may just be a css one

**Comment by mousemke** [comment]
actually wasnt working w/ normal data either.
