### ISSUE TITLE
request: reference to the passed unmodified complex options within flounder object

### ISSUE THREAD

**Issue by kevin-krug-sociomantic** [sociomantic-tsunami/flounder#69]
## Current 

as per version 0.6.3: when you instantiate flounder with complex options, e.g. inspired by docs (https://github.com/sociomantic-tsunami/flounder#building-the-select-box) with:
```
new Flounder( $('.selector')[0], 
{ 
  data: 
  [
    {
        header : 'header1',
        data : [ 'option1', 'option2', 'option3' ]
    },
    {
        text        : 'probably the string you want to see',
        value       : 'return value',
        description : 'a longer description of this element'
    },
    {
        header : 'header2',
        data : [ 'option1', 'option2' ]
   } );
  ]
} );
```
the instantiated Flounder object adds a index key to the stored data object:

![screen shot 2016-04-12 at 11 36 29](https://cloud.githubusercontent.com/assets/6839359/14456078/5919c604-00a3-11e6-99f9-e2ace519a823.png)

## Wanted 

reference to the unmodified passed options (no index key)

**Comment by mousemke** [comment]
@kevin-krug-sociomantic i'm not 100% on this.  what if the data in flounder changes? should the "originalData" be updated too?  should it be the original data, or the updated data in the original format?

i would initially suggest using the api functions to update your source data.  can you give me a more complex view of how this would work?

**Comment by kevin-krug-sociomantic** [comment]
@mousemke I see. The idea came up when exactly thinking about changing/dynamic data options. E.g. say the options are updated according to the change of a backbone model's attribute. In this case I would only want to rebuid flounder if the options changed and for this check the current options with respect to a reference, in the first case vs. the initial options. Reading the docs, I'd expect to get these from props (https://github.com/sociomantic-tsunami/flounder#api)  ```props the props set in the initial constructor``` (however they are altered via the addition of the index key).

**Comment by kevin-krug-sociomantic** [comment]
BTW. i'd be interested how you implement the ```index``` key in case of sectioned/nested options as in the above case (https://github.com/sociomantic-tsunami/flounder/issues/69#issue-147692900), I was assuming in your ```setByIndex``` method you'll have to flatten the option collection to a single level.
