### ISSUE TITLE
index key is not applied to all (complex/sectioned) options if text, value keys are not passed

### ISSUE THREAD

**Issue by kevin-krug-sociomantic** [sociomantic-tsunami/flounder#71]
first of all @mousemke thanks for sharing your great work and for constantly adding new features/improvements! 

## Current 

related https://github.com/sociomantic-tsunami/flounder/issues/70. as per version 0.6.3: when you instantiate flounder with complex(sectioned) options, e.g. inspired by docs (https://github.com/sociomantic-tsunami/flounder#building-the-select-box) with (without specifing ```{text:' ...', value’: '...'} ``` ):
```
new Flounder( $('.selector')[0], 
{ 
  data: 
  [
    {
        header : 'header1',
        data : [ 'option1', 'option2', 'option3' ]
    },
    {
        text        : 'probably the string you want to see',
        value       : 'return value',
        description : 'a longer description of this element'
    },
    {
        header : 'header2',
        data : [ 'option1', 'option2' ]
   } );
  ]
} );
``` 
the resulting Flounder object does not store all data objects with an index key:

![screen shot 2016-04-14 at 10 56 52](https://cloud.githubusercontent.com/assets/6839359/14522624/b8e73e94-022f-11e6-8286-de45672254d1.png)

it will if i would have passed:
```
data :
[
    {
        header : 'header1',
        data : [
        {
            text: 'option1',
            value: 'option1'
        },
        {
            text: 'option2',
            value: 'option3'
        },
        {
            text: 'option3',
            value:'option3'
        } ]
    },
    {
        text        : 'probably the string you want to see',
        value       : 'return value',
        description : 'a longer description of this element'
    },
    {
        header : 'header2',
        data : [
        {
            text: 'option1',
            value: 'option1'
        },
        {
            text:'option2',
            value:'option2'
        }
        ]
    }
] 
```

## Wanted 

support for the case that no text- and value keys are passed. support in the sense that you can retrieve the index of each option from the Flounder object (not just via data-index attribute of the dom options).

**Comment by mousemke** [comment]
#70 should have taken care of this too.  let me know if it doesnt and what else needs to be done, or let me know it can be closed
@kevin-krug-sociomantic

**Comment by kevin-krug-sociomantic** [comment]
@mousemke yep! looks like #70 took care of it!
