### ISSUE TITLE
setByValue: doesn't update to previous option

### ISSUE THREAD

**Issue by kevin-krug-sociomantic** [sociomantic-tsunami/flounder#74]
## Current

when instantiating flounder with array options, as so: 
```
var flounder = new Flounder($0,  {data:['a', 'b', 'c']});
```
and trying to reset the value programmatically as so: 
```
flounder.setByValue('b');
flounder.setByValue('a');
```
the current selected value is not updated back to a (default 1st option). 

## Wanted

fix this bug

**Comment by kevin-krug-sociomantic** [comment]
@mousemke thanks for the fix! the fix is quite important. when is the release schedualed which will include it?

**Comment by mousemke** [comment]
are #69 and #71 clear? i'd love to get 0.7.0 out today

**Comment by kevin-krug-sociomantic** [comment]
@mousemke sweat! will 0.7.0 have any breaking changes? i just checked out to ```0.7.0```. yes #69 and #70 look good!
