### ISSUE TITLE
flounder rebuild: not working as expected from the docs

### ISSUE THREAD

**Issue by kevin-krug-sociomantic** [sociomantic-tsunami/flounder#78]
According to the docs (https://github.com/sociomantic-tsunami/flounder) the API method ```rebuild( data, props )``` or ```this.rebuild( [ data, props ] )``` (? how should the args be passed) :

```rebuilds the select box options with new or altered data. If props are set, this completely rebuilds flounder```

## Current 

Rebuilding a flounder dropdown, when passing both data/dropdown options and props/all config options (passed as an array (passing the below as a list of two objects returns ```flounder.amd.js:1542 Uncaught TypeError: this.reconfigureFlounder is not a function(…)```) ), yields undefined options:
E.g. 
```
var flounder = new Flounder(<somediv>, {data:[1]});
flounder.rebuild([{data: [1,2,3] }, {data: [1,2,3], placeholder:'lala'}]);
```
yields:
![screen shot 2016-04-19 at 11 38 15](https://cloud.githubusercontent.com/assets/6839359/14634674/5b0bdd1e-0623-11e6-86fb-9ae659e8e402.png)

with the flounder object:

![screen shot 2016-04-19 at 11 38 50](https://cloud.githubusercontent.com/assets/6839359/14634680/63f07930-0623-11e6-9ee2-aa293baf190c.png)

## Wanted

clarification on the intended usage and possible fix of the above implementation case.

**Comment by mousemke** [comment]
fwiw the `[` and `]` denote optional params.  they will be removed in the next release

**Comment by mousemke** [comment]
ok.  at some point (0.4.x -> 0.5.0) reconfigure and rebuild became the same function w/ some detection.  reconfigureFlounder was renamed to reconfigure and there was a ref forgotten.  works locally now.  let me know if this doesnt work for your situation. (pull the `0.7.2` branch, you'll have to `npm run gulp`)

i wont release w/ just this unless someone **really** needs it AND really needs it to be an npm release

**Comment by mousemke** [comment]
(btw not pushed yet)

**Comment by kevin-krug-sociomantic** [comment]
regarding https://github.com/sociomantic-tsunami/flounder/issues/78#issuecomment-211985559: ok so both params are optional? 
regarding https://github.com/sociomantic-tsunami/flounder/issues/78#issuecomment-211991063: i does not work for my situation, the situation beeing as depicted above. Would be great if this fix could be released soon as a flounder binder I'm working on depends on it (as it uses the rebuild API method).

**Comment by kevin-krug-sociomantic** [comment]
@mousemke quickly glancing over your fix, is it safe to assume that your fix will only be relevant when using ```rebuild``` with the second argument ```props``` (as a intermediate solution until release of ```0.7.2```, I could thus refrain from this case for now)

**Comment by mousemke** [comment]
so w/ pics: 

![f1](https://cloud.githubusercontent.com/assets/1480168/14646807/40b9317c-065b-11e6-9d27-d2f9625ab0cd.png)

`var flounder = new Flounder( document.body, {data:[1]});`

![f2](https://cloud.githubusercontent.com/assets/1480168/14646812/45e831fc-065b-11e6-88c3-38a1610cc1ed.png)

'flounder.rebuild( [1,2,3 ], { data: [1,2,3 ], placeholder: 'lala' } );`

![f3](https://cloud.githubusercontent.com/assets/1480168/14647101/7e27844a-065c-11e6-9e2c-347862fca889.png)

i've left it as you called it but removed the confusing brackets, however i dont see why you would call the data twice.  it also works as  `flounder.rebuild([1,2,3], { placeholder:'lala'} );`

without the props also works: `flounder.rebuild( [1,2,3,4] );`

![f4](https://cloud.githubusercontent.com/assets/1480168/14647117/902896e8-065c-11e6-80c1-c1dbddb94bef.png)

as well as without the data : `flounder.rebuild( { data: [1,2,3], placeholder:'lala' } );` (defined in the props object)

![f5](https://cloud.githubusercontent.com/assets/1480168/14648064/c1e8e9e0-0660-11e6-867b-209d2dbd1d48.png)

as well as without defined data: `flounder.rebuild( { placeholder:'la' } );` (rebuild uses the current data)

![f8](https://cloud.githubusercontent.com/assets/1480168/14648142/174e8728-0661-11e6-847f-7ba83698b7b1.png)

as well as without either : `flounder.rebuild();` (rebuild w/ current options)

![f7](https://cloud.githubusercontent.com/assets/1480168/14647299/6a9cf0f8-065d-11e6-9767-cbd217422c6b.png)


(sorry if you just covered this.  saw there was a new comment while writing this)

**Comment by kevin-krug-sociomantic** [comment]
@mousemke thanks for the clarification! So I misunderstood. I thought ```props``` are all config options, so everything you would pass to flounder on instantiation, and should always include the data key, as defined in the docs (https://github.com/sociomantic-tsunami/flounder#api): "```props``` the props set in the initial constructor". So: 

- props do not necessarily have to include data in case of rebuild
- both data and props are optional 

However what is most crucial for me is the above all works after your FIX, correct? If I don't have your fix, since the current release is ```0.7.1``` I will have to avoid passing props, correct? All these considerations would be redundant if ```0.7.2``` could be released (as it would be great to be able to use the flounder rebuild implementation I'm working soon in production). Could you let me know when you plan on releasing it? Thanks!

**Comment by mousemke** [comment]
how about a trade?  I release 0.7.2 today, you PR a doc fix to make it more clear ^^

**Comment by kevin-krug-sociomantic** [comment]
@mousemke Agreed! Thanks man! :+1:

**Comment by kevin-krug-sociomantic** [comment]
@mousemke fyi. created pull request https://github.com/sociomantic-tsunami/flounder/pull/79. So that I understand it, it was just a matter of adding a few sentences. Cheers!
