### ISSUE TITLE
flounder rebuild: if props are passed, not only the passed are changed 

### ISSUE THREAD

**Issue by kevin-krug-sociomantic** [sociomantic-tsunami/flounder#81]
## Current 

now the flounder rebuild api method also resets props that are not passed as arguments: 

E.g.
```
var flounder = new Flounder(<yourselect>, {data: [1,2,3], selectDataOverride: true} );
flounder.rebuild([1,2], {onSelect: function(){console.log('selected')}});
```
yields:
```flounder.selectDataOverride``` is reset to ```false```. 

## Wanted

only the passed props should be altered. at least that's my request/suggestion/what i expected when using the api.

**Comment by mousemke** [comment]
given that the api method is called `.rebuild`, my feeling is that the data object you pass is the new data object.  I can leave this open for a couple days for discussion.

**Comment by kevin-krug-sociomantic** [comment]
@mousemke hmm.. discussable. I was just hoping ONLY the ```props``` you pass as 2nd argument are changed, not the ones not specified. But one could also have your pov and treat the passed props as the new props (analog to on instantiation), meaning all missing props are set to default. Hmmm..  discussable

**Comment by mousemke** [comment]
i think rebuild should stay how it is.  we could add another api function that took the passed props and extended the original props before passing it to rebuild

**Comment by tar-viturawong-sociomantic** [comment]
> given that the api method is called .rebuild, my feeling is that the data object you pass is the new data object. I can leave this open for a couple days for discussion.

@kevin-krug-sociomantic I agree with @mousemke, I cannot see a reason for `rebuild` to be "incremental", otherwise it would have been called `reconfigure`. It makes sense that the developer is fully responsible for holding the complete set of options for later use, and not use Flounder as surrogate for that.

**Comment by kevin-krug-sociomantic** [comment]
fair enough. thanks for contributing to the discussion @tar-viturawong-sociomantic
