### ISSUE TITLE
DISCUSSION: depreciate multiTag flounders

### ISSUE THREAD

**Issue by mousemke** [sociomantic-tsunami/flounder#88]
I'm not 100 on this one yet, but:

+ multiTag fields are non native behavior
+ they have subtle bugs all over the place
+ this would stream line and actually let us remove a bit of code from the core
+ do people use it?

this would simplify the approach inside the core and reduce the need for hacks to go around the multiTag's uniqueness

**Comment by kevin-krug-sociomantic** [comment]
@mousemke Yes, we have a use case for multitag selection coming up very soon. So at the time beeing, if flounder supports it, I would favour not removing it especially prior to investigation how well it works atm.

**Comment by mousemke** [comment]
cool.  then i def. support not removing it.  i'll look deeper into solving the weirdness issues (there arent _tons_)

**Comment by kevin-krug-sociomantic** [comment]
@mousemke sweet! :sweet_potato:

**Comment by emad-alam-sociomantic** [comment]
> multiTag fields are non native behavior

If you feel that flounder is a replacement/extended version of the native html [`select`](https://developer.mozilla.org/en/docs/Web/HTML/Element/select) tag, then  **multiple selection is a very very native behavior**, has always been.

**Comment by mousemke** [comment]
I don't suggest removing multiple selection, just the tagged style

![tagged style](http://pics.knoblau.ch/Flounder_demo_2016-06-07_19-36-43.png) 

as it has always been (internally) a bit funky.  But as long as people use it, refactoring may be the answer
