### ISSUE TITLE
Add specific class for placeholder element

### ISSUE THREAD

**Issue by andrei-placinta-sociomantic** [sociomantic-tsunami/flounder#90]
**Currently**
Placeholder element has the same class applied as other selected element.

**Wanted**
To be able to style placeholder (e.g. to mute it a bit) - add please a specific class for it.

**Comment by mousemke** [comment]
This actually already exists. As of yesterday, on the 0.8.0 branch. Hoping to release today; there's some multipleTags issues.

**Comment by andrei-placinta-sociomantic** [comment]
@mousemke great, thanks!
