### ISSUE TITLE
flounder demo broken

### ISSUE THREAD

**Issue by kevin-krug-sociomantic** [sociomantic-tsunami/flounder#92]
### current 

In order to test crossbrowser compatibilty or rather to test flounder in general it would be good to use the static html demo file you @mousemke kindly provide. I found some issues (tested IE10 and IE11, chrome) when testing via console:

- the `Flounder` constructor is not exposed
- no references to `flounder` instances of the target element e.g. via `document.querySelector( '#vanilla--select' ).flounder`
- mutliple broken dropdowns 

![screen shot 2016-06-14 at 18 38 18](https://cloud.githubusercontent.com/assets/6839359/16051251/41914924-325f-11e6-8083-8a7f64fec8ad.png)

ps sorry for buggin. I guess you are already working on the demo. 

### wanted

a dist file which works in browsers as per Doc support `(for modern browsers and ie9+)`

**Comment by mousemke** [comment]
thanks man! huge ie bug once compiled.  all good as of 0.8.2

https://github.com/sociomantic-tsunami/flounder/releases/tag/0.8.2
https://github.com/sociomantic-tsunami/flounder/commit/8f8d8baf5dc663e317cdb5c95431c28b9742288e
