### ISSUE TITLE
multiple tagged/multiple flounder bugs

### ISSUE THREAD

**Issue by kevin-krug-sociomantic** [sociomantic-tsunami/flounder#93]
### current 

concerning current release **flounder 0.8.2**:  when instantiating flounder with `multipleTags` or `multiple` options:

- multiple selection does not consistently work
- ~~options are removed once **selected**~~

Example:

say you instantiate a flounder instance in the console (with Flounder constructor exposed to global window):
`new Flounder($0, {data: [1,2,3], multipleTags: true})`
targeting `$0` beeing an empty `<div>` tag you previously inspected. 

Example Interactions:

you select the 1st option:
![screen shot 2016-06-20 at 12 58 57](https://cloud.githubusercontent.com/assets/6839359/16192122/c8111678-36e7-11e6-925f-1a2abba5a330.png)
result (expected):
![screen shot 2016-06-20 at 13 02 22](https://cloud.githubusercontent.com/assets/6839359/16192136/d8ba3ee6-36e7-11e6-9500-f685295d4c47.png)
now you select the 2nd (~~**unexpected**~~ 1st option is missing in the dropdown)
![screen shot 2016-06-20 at 13 02 26](https://cloud.githubusercontent.com/assets/6839359/16192161/f82217e0-36e7-11e6-91fa-9551373db379.png)
result (**unexpected** 1st option is removed from the selected, 2nd options for the options)
![screen shot 2016-06-20 at 13 02 37](https://cloud.githubusercontent.com/assets/6839359/16192176/0ac68fa2-36e8-11e6-9b69-8c8114f3d9ed.png)
result after selecting the 3rd option (~~**unexpected**~~: all previously selected options are missing, as is the 1st option in the selected list):
![screen shot 2016-06-20 at 13 02 45](https://cloud.githubusercontent.com/assets/6839359/16192198/27044970-36e8-11e6-9913-f9ee13decf57.png)

### wanted 

clarification of a possible misimplementation or of the expected behaviour or if these are bugs, can you please check, thanks!

**Comment by mousemke** [comment]
options are very intentionally hidden.  since they are represented above, there is no reason to represent them twice.  this behavior can be overridden by setting a custom class to `flounder__option--selected--hidden` (see config options)

as far as (in this case) `1` being selected but disappearing from both places, i am unable to reproduce that.  can you please double check the version and that it is reproducible, then post the html structure?

**Comment by kevin-krug-sociomantic** [comment]
@mousemke yes you are correct, 
>  since they are represented above, there is no reason to represent them twice
this makes sense and is expected behaviour. Should of given this more thought before issuing it. My bad! Sorry about that!

As of the first option `1` disappearing when selecting the 2nd option, I was able to reproduce. The html structure in the above exampel is literally `<div></div>`. And then inspecting it (caching the dom element as `$0` in the console) and instantiating flounder with it as target via: new Flounder($0, {data: [1,2,3], multipleTags: true}) (having exposed `window.Flounder`= `Flounder` on project init)

**Comment by mousemke** [comment]
anything in the console?

**Comment by kevin-krug-sociomantic** [comment]
@mousemke nope, no error that is. On instantiation the flounder option is returned. But on selection there's no console output.

**Comment by kevin-krug-sociomantic** [comment]
@mousemke how did you try to reproduce. fyi (don't know if this helps at all, but...). I also tested with js-hooked markup `<div class="js-flounder-test"></div>` and js `new Flounder($('.js-flounder-test')[0], {data: [1,2,3], multipleTags: true})`. issue was reproducable with this example as well

**Comment by mousemke** [comment]
browser?

**Comment by kevin-krug-sociomantic** [comment]
@mousemke oh yes, sorry for not mentioning. latest chrome. `Version 50.0.2661.94 (64-bit)`

**Comment by kevin-krug-sociomantic** [comment]
@mousemke thanks for looking into this! i just also noticed that the selected list is always reset when trying to select a 3rd option. noticed when extending above example by more options (`new Flounder($0, {data: [1,2,3,4,5,6,7,8,9,10], multipleTags: true});`)

after having selected options (`1`) `2` and `3` and selecting `4` 
![screen shot 2016-06-20 at 16 19 14](https://cloud.githubusercontent.com/assets/6839359/16197601/023b44b6-3703-11e6-8ab2-67940da37bca.png)
results in:
![screen shot 2016-06-20 at 16 21 37](https://cloud.githubusercontent.com/assets/6839359/16197630/16cf9e5e-3703-11e6-87a8-3c31e63ab8de.png)

**Comment by mousemke** [comment]
such confuse… still unable to duplicate. not happening here on canary ( 53.0.2750.0  ) or normal chrome ( 51.0.2704.103 ).  can pull `dev`and try it with that?

**Comment by kevin-krug-sociomantic** [comment]
@mousemke i'm using current flounder `0.8.2` release, at commit `1fa741679393b89d488d84678811ed942f821ae4`. Did you try checking out to that commit? when updating my `package.json` to point to `git+ssh://git@github.com/sociomantic/flounder.git#master` (i assume that's what you refer to as `dev` as i couldn't find a `dev` branch) i get a require script error for flounder. (http://requirejs.org/docs/errors.html#scripterror)

**Comment by mousemke** [comment]
+ as dev i guess i mean `0.8.3` (latest non released version branch) though i should have been more specific

+ it's not an issue due to github being smart, but you should update `package.json` to use `sociomantic-tsunami`

+ what's your `require.js` call look like? have other Soc. people looked at this?  is there a more specific error? i have not seen any require errors on my side (and that's how we use it in our frontend as well)

other than that, i'm still digging into this one.

**Comment by kevin-krug-sociomantic** [comment]
@mousemke FALSE ALARM! it's not a flounder bug! it was a conflict with a global j query valiator rule, a trim rule which removed options

**Comment by mousemke** [comment]
something something global variables...

glad it's not a bug and (more for your sake) the problem is found
