### ISSUE TITLE
console log in addPlaceholder method

### ISSUE THREAD

**Issue by kevin-krug-sociomantic** [sociomantic-tsunami/flounder#95]
### wanted 

remove console log https://github.com/sociomantic-tsunami/flounder/blob/master/src/core/events.js#L111

**Comment by mousemke** [comment]
this is removed in dev (`0.8.3`), but feel free to make a PR

**Comment by kevin-krug-sociomantic** [comment]
okay perfect, was referring to current release `0.8.2` https://github.com/sociomantic-tsunami/flounder/releases. so i'll wait for release `0.8.3` cheers
