### ISSUE TITLE
Backspace on Flounder multiselect does not delete the most recent selection

### ISSUE THREAD

**Issue by zsolt-nagy-sociomantic** [sociomantic-tsunami/flounder#96]
***Currently***
When one or more elements have been added to a multiselect, and there is no new item being selected by typing text, then backspace does not do anything.

***Wanted***
Delete the most recent selection on backspace in case there is no text entered for selecting another item.

**Comment by mousemke** [comment]
you mean on tagged multiselect?

**Comment by kevin-krug-sociomantic** [comment]
@mousemke yes `multipleTags : true`

**Comment by mousemke** [comment]
so.  i dont think i'll get to this til after the weekend, but i have a proposed interaction.  this will also help in accessibility of multiTag flounders.

+ make tags tab able
	+ they will each need a tabindex of 0
	+ they will each need a role (deselect <option name>)
	+ they will need a `focus` border
	+ now is a good time to give them a `hover` border

+ backspace on an empty search will focus the last selected tag

+ a second backspace, a space, or enter will remove the tag

+ after tag removal, focus will return to either: *(this is the interaction i'm unsure of)*
	+ the input
	+ the next last tag

thoughts? @zsolt-nagy-sociomantic

**Comment by zsolt-nagy-sociomantic** [comment]
@mousemke 
- regarding tabbing, not all browsers will accept it, especially if Safari users ban it in their settings. Yet, in most browsers, it will be fine.
- the second and the third point make perfect sense, and it highlights the importance of the first point (selecting via tagging) too
- in my opinion, after tag removal, focusing on the "next last tag" makes slightly more sense, and if there are no more tags left, then we fall back to focusing on the input field. This will save some backspace keys for the user in case they want to delete multiple tags.

One more remark is that suppose you have 4 tags, you focus on the second, then you delete it, which tag will then be focused afterwards?

**Comment by mousemke** [comment]
tabbing is super important as some people cant use mic.  if people have it disabled, that's their issue

i would say that if the second one is deleted it goes back to the first, (i.e. the same direction that the input to last one, etc is)

**Comment by zsolt-nagy-sociomantic** [comment]
@mousemke, based on your rule, suppose you have 4 tags, `A`, `B`, `C`, `D`, and before pressing backspace, you are focused on:
- `A`. Then the newly selected item will be `B`
- `B`. Then the newly selected item will be `A`
- `C`. Then the newly selected item will be `B`
- `D`. Then the newly selected item will be `C`

In other words, the index of the selected item stays the same if you delete the first item, and is decreased by one otherwise.

**Comment by zsolt-nagy-sociomantic** [comment]
Thank you, @mousemke.

**Comment by mousemke** [comment]
for sure.  to be clear, you wont see this until 1.0.0 but feel free to pull the branch and check it out. lemme know if you have any observations on the interaction

in addition to the above, if you type until there's only one option and hit enter, that will be selected

**Comment by kevin-krug-sociomantic** [comment]
@mousemke coolio! when's ca. the ETA for eagerly awaited `1.0.0`?

**Comment by mousemke** [comment]
well.... [refactoring](https://github.com/sociomantic-tsunami/flounder/issues/101) is still an issue, as well i'd *really* like to [get to 100% test coverage](https://github.com/sociomantic-tsunami/flounder/issues/55).  If I think I can find time to make solid progress then I'll do them for 1.0.0, but I wont let it sit untouched for a long time.  In that case would drop the tests and release earlier
