### ISSUE TITLE
deselectAll() does not remove selected options for multitagged flounder

### ISSUE THREAD

**Issue by kevin-krug-sociomantic** [sociomantic-tsunami/flounder#97]
tested in the flounder `demo /index.html`

`$0` beeing `<input class="vanilla--input--tags  flounder--hidden" id="vanilla--input--tags" type="text" aria-hidden="true" tabindex="-1">`

when calling:

`$0.flounder.deselectAll()`

`$0.flounder.getSelectedValues()`
returns `[]`

however the options are still presented as beeing selected:

![screen shot 2016-06-23 at 16 24 12](https://cloud.githubusercontent.com/assets/6839359/16306828/53402576-395f-11e6-8370-645437362644.png)

**Comment by mousemke** [comment]
true

**Comment by mousemke** [comment]
good catch

https://github.com/sociomantic-tsunami/flounder/releases/tag/0.8.3
